name: Shellcheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: shellcheck
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-general/.github/workflows/general-shellcheck.yml@3858e9e74c805067e454740b195372c7195f333b # v1.5.0
    with:
      working-directory: .
